/*
 * Shared helpers for the host-side conversion tool.
 *
 * SPDX-License-Identifier: MIT
 */

#include "codec_utils.h"

#include <stdlib.h>
#include <string.h>

int pud_write_codec_header(FILE *out, const char *codec,
			   const char *array_name, const char *source_name,
			   int width, int height, const uint8_t *data,
			   size_t size, size_t raw_size)
{
	size_t i;

	if (out == NULL || codec == NULL || array_name == NULL || data == NULL)
		return -1;

	fprintf(out,
		"/*\n"
		" * Auto-generated by pudcodec (Pico USB Display).\n"
		" * Source: %s\n"
		" * Codec: %s\n"
		" * Dimensions: %d x %d\n"
		" * Raw size: %zu bytes, compressed: %zu bytes (%.1f%%)\n"
		" */\n\n",
		source_name != NULL ? source_name : "(unknown)", codec,
		width, height, raw_size, size,
		raw_size > 0u ? (double)size / (double)raw_size * 100.0 : 0.0);

	fprintf(out, "#include <stdint.h>\n\n");

	fprintf(out,
		"#define %s_CODEC  \"%s\"\n"
		"#define %s_WIDTH  %d\n"
		"#define %s_HEIGHT %d\n"
		"#define %s_PIXELS %d\n"
		"#define %s_SIZE   %zuu\n\n",
		array_name, codec,
		array_name, width,
		array_name, height,
		array_name, width * height,
		array_name, size);

	fprintf(out, "static const uint8_t %s[%zu] = {\n", array_name, size);

	for (i = 0u; i < size; i++) {
		if ((i & 0x0Fu) == 0u)
			fputs("\t", out);
		fprintf(out, "0x%02X", (unsigned int)data[i]);
		if (i + 1u < size)
			fputc(',', out);
		if ((i & 0x0Fu) == 0x0Fu)
			fputc('\n', out);
		else if (i + 1u < size)
			fputc(' ', out);
	}

	if ((size & 0x0Fu) != 0u)
		fputc('\n', out);

	fprintf(out, "};\n");
	return 0;
}

int pud_write_binary(FILE *out, const uint8_t *data, size_t size)
{
	if (out == NULL || data == NULL)
		return -1;

	return fwrite(data, 1u, size, out) == size ? 0 : -1;
}

int pud_write_video_header(FILE *out, const char *codec, const char *base_name,
			   int width, int height, uint8_t *const *frames,
			   const size_t *sizes, int frame_count,
			   size_t total_raw)
{
	size_t total_comp = 0u;
	size_t global = 0u;
	int f;
	size_t i;

	if (out == NULL || codec == NULL || base_name == NULL || frames == NULL ||
	    sizes == NULL || frame_count <= 0)
		return -1;

	for (f = 0; f < frame_count; f++)
		total_comp += sizes[f];

	fprintf(out,
		"/*\n"
		" * Auto-generated by pudcodec (Pico USB Display).\n"
		" * Codec: %s\n"
		" * Frames: %d, dimensions: %d x %d\n"
		" * Raw total: %zu bytes, compressed total: %zu bytes (%.1f%%)\n"
		" */\n\n",
		codec, frame_count, width, height, total_raw, total_comp,
		total_raw > 0u ? (double)total_comp / (double)total_raw * 100.0
			       : 0.0);

	fprintf(out, "#include <stdint.h>\n\n");

	fprintf(out,
		"#define %s_CODEC       \"%s\"\n"
		"#define %s_WIDTH       %d\n"
		"#define %s_HEIGHT      %d\n"
		"#define %s_PIXELS      %d\n"
		"#define %s_FRAME_COUNT %d\n"
		"#define %s_FRAME0_SIZE %zuu\n"
		"#define %s_TOTAL_SIZE  %zuu\n\n",
		base_name, codec,
		base_name, width,
		base_name, height,
		base_name, width * height,
		base_name, frame_count,
		base_name, sizes[0],
		base_name, total_comp);

	fprintf(out, "/* Byte offset of each frame in %s_FRAMES[] */\n",
		base_name);
	fprintf(out, "static const uint32_t %s_FRAME_OFFSETS[%d+1] = {\n",
		base_name, frame_count);

	{
		size_t off = 0u;

		for (f = 0; f <= frame_count; f++) {
			fprintf(out, "\t%zuu", off);
			if (f < frame_count) {
				off += sizes[f];
				fputs(",\n", out);
			} else {
				fputs("\n", out);
			}
		}
	}
	fprintf(out, "};\n\n");

	fprintf(out, "/* Concatenated %s frames */\n", codec);
	fprintf(out, "static const uint8_t %s_FRAMES[%zu] = {\n",
		base_name, total_comp);

	for (f = 0; f < frame_count; f++) {
		fprintf(out, "\t/* --- frame %d --- */\n", f);
		for (i = 0u; i < sizes[f]; i++) {
			if ((global & 0x0Fu) == 0u)
				fputs("\t", out);
			fprintf(out, "0x%02X", (unsigned int)frames[f][i]);
			global++;
			if (global < total_comp)
				fputc(',', out);
			if ((global & 0x0Fu) == 0x0Fu)
				fputc('\n', out);
			else if (global < total_comp)
				fputc(' ', out);
		}
		if ((global & 0x0Fu) != 0u)
			fputc('\n', out);
	}

	fprintf(out, "};\n");
	return 0;
}

int pud_write_video_binary(FILE *out, uint8_t *const *frames,
			   const size_t *sizes, int frame_count)
{
	uint32_t count, offset;
	int f;

	if (out == NULL || frames == NULL || sizes == NULL || frame_count <= 0)
		return -1;

	count = (uint32_t)frame_count;
	if (fwrite(&count, sizeof(count), 1u, out) != 1u)
		return -1;

	offset = (uint32_t)(sizeof(count) + (size_t)(frame_count + 1) * 4u);
	if (fwrite(&offset, sizeof(offset), 1u, out) != 1u)
		return -1;

	for (f = 0; f < frame_count; f++) {
		offset += (uint32_t)sizes[f];
		if (fwrite(&offset, sizeof(offset), 1u, out) != 1u)
			return -1;
	}

	for (f = 0; f < frame_count; f++) {
		if (fwrite(frames[f], 1u, sizes[f], out) != sizes[f])
			return -1;
	}

	return 0;
}

uint8_t *pud_read_file(const char *path, size_t *size)
{
	FILE *fp;
	long len;
	uint8_t *buf;

	if (path == NULL || size == NULL)
		return NULL;

	fp = fopen(path, "rb");
	if (fp == NULL) {
		fprintf(stderr, "pudcodec: cannot open '%s'\n", path);
		return NULL;
	}

	if (fseek(fp, 0L, SEEK_END) != 0 || (len = ftell(fp)) < 0L ||
	    fseek(fp, 0L, SEEK_SET) != 0) {
		fprintf(stderr, "pudcodec: cannot size '%s'\n", path);
		fclose(fp);
		return NULL;
	}

	buf = malloc((size_t)len + 1u);
	if (buf == NULL) {
		fclose(fp);
		return NULL;
	}

	if (fread(buf, 1u, (size_t)len, fp) != (size_t)len) {
		fprintf(stderr, "pudcodec: short read on '%s'\n", path);
		free(buf);
		fclose(fp);
		return NULL;
	}
	fclose(fp);
	buf[len] = '\0';
	*size = (size_t)len;
	return buf;
}

const char *pud_basename(const char *path)
{
	const char *slash = strrchr(path, '/');
	const char *back = strrchr(path, '\\');

	if (back != NULL && (slash == NULL || back > slash))
		slash = back;

	return slash != NULL ? slash + 1 : path;
}

/*
 * A C identifier from a file name: "dir/boot logo.rle.h" -> "boot_logo".  The
 * name stops at the first dot, so the codec suffix and ".h" of a generated
 * header do not end up in the identifier.
 */
void pud_array_name(const char *path, char *out, size_t out_size)
{
	const char *base = pud_basename(path);
	size_t i;

	if (out_size == 0u)
		return;

	for (i = 0u; i + 1u < out_size && base[i] != '\0' && base[i] != '.'; i++) {
		char c = base[i];

		if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
		    (c >= '0' && c <= '9'))
			out[i] = c;
		else
			out[i] = '_';
	}
	out[i] = '\0';
}

void pud_output_name(const char *input, const char *ext, char *out,
		     size_t out_size)
{
	const char *dot = strrchr(input, '.');
	size_t base_len = dot != NULL ? (size_t)(dot - input) : strlen(input);
	size_t ext_len = strlen(ext);

	if (base_len > out_size - ext_len - 1u)
		base_len = out_size - ext_len - 1u;

	memcpy(out, input, base_len);
	out[base_len] = '\0';
	strcat(out, ext);
}

/*
 * Find the value of a numeric define whose name ends in `suffix`.  Only the
 * leading decimal digits are read, which is enough for the generated headers.
 */
long pud_parse_define(const char *text, const char *suffix, long fallback)
{
	const char *p = text;
	size_t suffix_len = strlen(suffix);

	while ((p = strstr(p, "#define ")) != NULL) {
		const char *name = p + 8u;
		const char *name_end;
		size_t name_len;

		while (*name == ' ' || *name == '\t')
			name++;
		name_end = name;
		while (*name_end != '\0' && *name_end != ' ' &&
		       *name_end != '\t' && *name_end != '\r' &&
		       *name_end != '\n')
			name_end++;

		name_len = (size_t)(name_end - name);
		if (name_len > suffix_len &&
		    strncmp(name_end - suffix_len, suffix, suffix_len) == 0) {
			if (*name_end != '\0' && *name_end != '\n' &&
			    *name_end != '\r') {
				long value = strtol(name_end, NULL, 10);

				return value;
			}
		}
		p += 8u;
	}

	return fallback;
}

int pud_parse_define_str(const char *text, const char *suffix, char *out,
			 size_t out_size)
{
	const char *p = text;
	size_t suffix_len = strlen(suffix);

	while ((p = strstr(p, "#define ")) != NULL) {
		const char *name = p + 8u;
		const char *name_end;
		const char *quote;
		size_t name_len;

		while (*name == ' ' || *name == '\t')
			name++;
		name_end = name;
		while (*name_end != '\0' && *name_end != ' ' &&
		       *name_end != '\t' && *name_end != '\r' &&
		       *name_end != '\n')
			name_end++;

		name_len = (size_t)(name_end - name);
		if (name_len > suffix_len &&
		    strncmp(name_end - suffix_len, suffix, suffix_len) == 0) {
			quote = strchr(name_end, '"');
			if (quote != NULL) {
				const char *end = strchr(quote + 1, '"');
				size_t len;

				if (end == NULL)
					return 0;
				len = (size_t)(end - quote - 1);
				if (len >= out_size)
					len = out_size - 1u;
				memcpy(out, quote + 1, len);
				out[len] = '\0';
				return 1;
			}
		}
		p += 8u;
	}

	return 0;
}

/*
 * Take the bytes of the last `static const uint8_t ...[...] = { ... }` array.
 * The video headers put the concatenated frames last, so this picks the frame
 * data and not the offset table.
 */
size_t pud_parse_codec_array(const char *text, uint8_t *out, size_t capacity)
{
	const char *decl = NULL;
	const char *p = text;
	const char *brace;
	size_t count = 0u;

	while ((p = strstr(p, "uint8_t ")) != NULL) {
		decl = p;
		p += 8u;
	}
	if (decl == NULL)
		return 0u;

	brace = strchr(decl, '{');
	if (brace == NULL)
		return 0u;

	p = brace;
	while (*p != '\0' && count < capacity) {
		if (p[0] == '0' && (p[1] == 'x' || p[1] == 'X') &&
		    p[2] != '\0' && p[3] != '\0') {
			unsigned int value;
			char hex[3] = { p[2], p[3], '\0' };

			if (sscanf(hex, "%2x", &value) == 1) {
				out[count++] = (uint8_t)value;
				p += 4;
				continue;
			}
		}
		if (*p == '}')
			break;
		p++;
	}

	return count;
}

void pud_print_size_comparison(const char *label, size_t raw_bytes,
			       size_t compressed_bytes)
{
	double ratio = raw_bytes > 0u
			       ? (double)compressed_bytes / (double)raw_bytes *
					 100.0
			       : 0.0;

	printf("  %-28s raw: %9zu B  encoded: %9zu B  (%5.1f%%", label,
	       raw_bytes, compressed_bytes, ratio);
	if (compressed_bytes < raw_bytes)
		printf(", %.1f%% saved", 100.0 - ratio);
	else if (compressed_bytes > raw_bytes)
		printf(", expanded by %.1f%%", ratio - 100.0);
	printf(")\n");
}
